"""Export cafein's shipped default emission factors as the bundled CSV.

The asset carries no new numbers: it is a mechanical export of
``cafein.emissions.default_factors()`` (transit rows),
``street_factors()`` (street rows), and ``vehicle_class_factors()``
(the per-powertrain building blocks) — same values, same source (Dey,
Marín-Flores & Tenkanen 2026, doi:10.1016/j.scs.2026.107226). Two
files: ``emission_factors.csv``, the transit defaults alone in exactly
the ``cafein.emissions.load_factors`` schema, and
``emission_factors_full.csv``, the three-table reference under a
``table`` column with a per-row ``source`` citation.

Regenerated by running this module against the installed cafein; the
test suite asserts the bundled file byte-equals a fresh export, so the
CSV can never drift from the library.
"""

from __future__ import annotations

import argparse
import pathlib

from pipeline import PipelineError

CITATION = "Dey, Marín-Flores & Tenkanen (2026), doi:10.1016/j.scs.2026.107226"

#: Where the bundled assets live inside the helsinki subpackage:
#: the loader-ready transit table, and the full three-table reference.
DATA_DIR = (
    pathlib.Path(__file__).resolve().parent.parent
    / "cafein"
    / "sampledata"
    / "helsinki"
    / "data"
)
BUNDLED_PATH = DATA_DIR / "emission_factors.csv"
BUNDLED_FULL_PATH = DATA_DIR / "emission_factors_full.csv"

COLUMNS = [
    "table",
    "trip_id",
    "route_id",
    "agency_id",
    "route_type",
    "street_mode",
    "vehicle_class",
    "service_model",
    "vehicle",
    "fuel",
    "infrastructure",
    "operations",
    "source",
]


def factors_frame():
    """The export frame, deterministic row and column order."""
    try:
        import pandas
        from cafein import emissions
    except ImportError as error:
        raise PipelineError(
            "the factors export needs cafein (see pipeline/environment.yaml)"
        ) from error
    transit = emissions.default_factors()
    transit.insert(0, "table", "transit")
    street = emissions.street_factors()
    street.insert(0, "table", "street")
    classes = emissions.vehicle_class_factors().reset_index()
    classes.insert(0, "table", "vehicle_class")
    frame = pandas.concat([transit, street, classes], ignore_index=True)
    frame["source"] = CITATION
    frame = frame.reindex(columns=COLUMNS)
    # Concat floats the GTFS route_type through the street rows' gaps;
    # keep it the integer code the spec defines.
    frame["route_type"] = frame["route_type"].astype("Int64")
    return frame


TRANSIT_COLUMNS = [
    "trip_id",
    "route_id",
    "agency_id",
    "route_type",
    "vehicle",
    "fuel",
    "infrastructure",
    "operations",
]


def render_full_csv() -> str:
    """The three-table reference file's exact text."""
    return factors_frame().to_csv(index=False, lineterminator="\n")


def render_csv() -> str:
    """The loader-ready file's exact text: the transit section in
    exactly the schema ``cafein.emissions.load_factors`` consumes —
    street and per-powertrain rows would read as conflicting global
    defaults there, so they live in the full file only."""
    frame = factors_frame()
    transit = frame[frame["table"] == "transit"].reindex(columns=TRANSIT_COLUMNS)
    return transit.to_csv(index=False, lineterminator="\n")


def write_factors(directory=DATA_DIR) -> tuple:
    directory = pathlib.Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    loader_ready = directory / BUNDLED_PATH.name
    full = directory / BUNDLED_FULL_PATH.name
    # Bytes, not text mode: the byte-equality contract must not bend to
    # platform newline translation.
    loader_ready.write_bytes(render_csv().encode("utf-8"))
    full.write_bytes(render_full_csv().encode("utf-8"))
    return loader_ready, full


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DATA_DIR), help="destination directory")
    arguments = parser.parse_args()
    print(write_factors(arguments.out))
